[LOGGER]
stdout_lvl = ""  # "TRACE" | "DEBUG" | "INFO" | "SUCCESS" | "WARNING" | "ERROR" | "CRITICAL"
environnement = ""  # "DEV" | "PROD"

[DISCORD]
prefix = ""
client_id = ""
guild_ids = [""]
token = ""

[SPOTIFY]
spotify_id = ""
spotify_secret = ""
